<h1>Connexion</h1>
<hr/>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <form name="formLogin" method="post" action="">
            <input type="hidden" name="csrf_token" value="<?= $token; ?>"/>
            <div class="form-group">
                <div class="input-group">
          <span class="input-group-addon" id="basic-username"> 
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span> 
          </span>
                    <input name="username" type="text" class="form-control" placeholder="Nom d'utilisateur"
                           aria-describedby="basic-username">
                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
          <span class="input-group-addon" id="basic-pwd"> 
            <span class="glyphicon glyphicon-lock" aria-hidden="true"></span> 
          </span>
                    <input name="password" type="password" class="form-control" placeholder="Mot de passe"
                           aria-describedby="basic-pwd">
                </div>
            </div>
            <button name="connexion" type="submit" class="btn btn-success">Connexion</button>
            <br/>
            Pas encore de compte ?
            <a href="<?= getUrl('registration'); ?>">Enregistrez vous ici</a>
        </form>
    </div>
</div>