<h1>Déconnexion</h1>
<hr/>
<div class="row">
  <div class="col-lg-12 center">
    <form method="post" name="logoutForm" action="">
      Etes vous sur de vouloir vous déconnecter ?
      <input type="hidden" name="csrf_token" value="<?= $token; ?>"/>
      <button class="btn btn-success" type="submit" name="deconnexion">Oui</button>
      <a class="btn btn-danger" href="<?= BASE_URL; ?>">Non</a>
    </form>
  </div>
</div>