<div>
    <h1>Réinitialisation de votre mot de passe</h1>
    <div class="row">
        <div class="col-md-6 col-md-offset-2">
            <form name="<?= $reset_password_form->name; ?>" method="<?= $reset_password_form->method; ?>"
                  action="<?= $reset_password_form->action; ?>">
                <?php foreach ($reset_password_form->elements as $element): ?>
                    <?= $element; ?>
                <?php endforeach; ?>
            </form>
        </div>
    </div>
</div>