<h1>Réinitialisation de votre mot de passe</h1>
<hr/>
<div class="row">
  <div class="col-lg-12">
    <form name="reset_password_form" method="post" action="">
      <input type="hidden" name="csrf_token" value="<?= $token; ?>"/>
      <div class="form-group">
        <div class="input-group">
          <span class="input-group-addon" id="basic-username">
            <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
          </span><input name="email" type="email" class="form-control" placeholder="Votre adresse email" aria-describedby="basic-username">
        </div>
      </div>
      <button name="connexion" type="submit" class="btn btn-success">Envoyer l'email de réinitialisation de mot de passe</button>
    </form>
  </div>
</div>