<h1>Modification du mot de passe</h1>
<hr>
<div class="row">
    <div class="col-md-6">
        <form name="<?= $updatePasswordForm->name; ?>" method="<?= $updatePasswordForm->method; ?>"
              action="<?= $updatePasswordForm->action; ?>">
            <?php foreach ($updatePasswordForm->elements as $element): ?>
                <?= $element; ?>
            <?php endforeach; ?>
            <a class="btn btn-danger" href="<?= getUrl('profil'); ?>">Annuler</a>
        </form>
    </div>
</div>