<div>
    <p>
        Catégorie : <?= $values['categorie_contact']; ?>
    </p>
    <p>
        Message envoyé depuis la page de contact de <?= SITE_NAME; ?>
    </p>
    <p>
        De la part de : <?= $values['nom_contact'] . ' ' . $values['prenom_contact']; ?>
    </p>
    <p>
        Email renseigné : <a href="mailto:<?= $values['email_contact']; ?>"><?= $values['email_contact']; ?></a>
    </p>
    <p>
        Message : <br/><?= $values['message_contact']; ?>
    </p>
</div>