<!DOCTYPE html>
<html>
<!-- Header -->
<head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8"/>
    <?php require ROOT . DS . 'views' . DS . 'templates' . DS . 'blocks' . DS . 'head.phtml'; ?>
    <title>Erreur HTTP/1.0 404</title>
</head>
<!-- Fin header -->
<body>
<div class="container-fluid">
    <header>
        <!-- Navbar -->
        <?php require ROOT . DS . 'views' . DS . 'templates' . DS . 'blocks' . DS . 'navbar.phtml'; ?>
        <!-- Fin navbar -->
        <section>
            <div class="row">
                <!-- Corps de page -->
                <div class="col-md-12 corps">
                    <div class="alert alert-danger center _404">
                        <h1>
                            HTTP/1.0 404 Not Found<br/>
                            Cette page n'éxiste pas<br/>
                        </h1>
                    </div>
                </div>
                <!-- Fin corps de page -->
            </div>
        </section>
        <footer>
            <!-- Pied de page -->
            <?php require ROOT . DS . 'views' . DS . 'templates' . DS . 'blocks' . DS . 'footer.phtml'; ?>
            <!-- Fin pied de page -->
        </footer>
</div>
<?php require ROOT . DS . 'views' . DS . 'templates' . DS . 'blocks' . DS . 'scripts.phtml'; ?>
</body>
</html>