<!DOCTYPE html>
<html>
  <!-- Header -->
  <head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8"/>
    <?php require ROOT . DS . 'views' . DS . 'templates' . DS . 'blocks' . DS . 'head.phtml'; ?>
    <link href="https://fonts.googleapis.com/css?family=Faster+One|Noto+Sans|Quattrocento" rel="stylesheet">
    <title>Erreur HTTP/1.0 404</title>
  </head>
  <!-- Fin header -->
  <body>
    <div class="container-fluid">
      <header>
      </header>
      <section>
        <div class="row justify-content-md-center">
          <!-- Corps de page -->
          <div class="col-md-6 corps">
            <div class="alert alert-danger center _404">
              <h1>
                HTTP/1.0 404 Not Found<br/>
                Cette page n'éxiste pas<br/>
              </h1>
              <h3>
                <a href="<?= BASE_URL; ?>" style="text-decoration: none;">Retourner à la page d'accueil</a>
              </h3>
            </div>
          </div>
          <!-- Fin corps de page -->
        </div>
      </section>
    </div>
  </body>
</html>