<div class="row">
    <div class="col-md-6">
        <h1>Lorem</h1>
        <hr/>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam porttitor mauris sed hendrerit feugiat. In hac
            habitasse platea dictumst. Fusce luctus quis odio a bibendum. In pulvinar mauris non porttitor sagittis.
            Quisque ut ex at augue pellentesque feugiat. In luctus quis sapien id pretium. Morbi ut commodo libero, non
            egestas ipsum. Nullam commodo leo ultrices magna hendrerit, at vehicula velit pellentesque. Maecenas tellus
            ipsum, posuere fringilla scelerisque vitae, tristique sed lectus.
        </p>
    </div>
    <div class="col-md-6">
        <h1>Lorem</h1>
        <hr/>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam porttitor mauris sed hendrerit feugiat. In hac
            habitasse platea dictumst. Fusce luctus quis odio a bibendum. In pulvinar mauris non porttitor sagittis.
            Quisque ut ex at augue pellentesque feugiat. In luctus quis sapien id pretium. Morbi ut commodo libero, non
            egestas ipsum. Nullam commodo leo ultrices magna hendrerit, at vehicula velit pellentesque. Maecenas tellus
            ipsum, posuere fringilla scelerisque vitae, tristique sed lectus.
        </p>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <h1>Lorem</h1>
        <hr/>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam porttitor mauris sed hendrerit feugiat. In hac
            habitasse platea dictumst. Fusce luctus quis odio a bibendum. In pulvinar mauris non porttitor sagittis.
            Quisque ut ex at augue pellentesque feugiat. In luctus quis sapien id pretium. Morbi ut commodo libero, non
            egestas ipsum. Nullam commodo leo ultrices magna hendrerit, at vehicula velit pellentesque. Maecenas tellus
            ipsum, posuere fringilla scelerisque vitae, tristique sed lectus.
        </p>
    </div>
    <div class="col-md-6">
        <h1>Lorem</h1>
        <hr/>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam porttitor mauris sed hendrerit feugiat. In hac
            habitasse platea dictumst. Fusce luctus quis odio a bibendum. In pulvinar mauris non porttitor sagittis.
            Quisque ut ex at augue pellentesque feugiat. In luctus quis sapien id pretium. Morbi ut commodo libero, non
            egestas ipsum. Nullam commodo leo ultrices magna hendrerit, at vehicula velit pellentesque. Maecenas tellus
            ipsum, posuere fringilla scelerisque vitae, tristique sed lectus.
        </p>
    </div>
</div>