<section class="row pied">
  <div class="col-lg-3 col-sm-12 parts-left">
    <h3>A propos</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam porttitor mauris sed hendrerit feugiat. In hac habitasse platea dictumst. Fusce luctus quis odio a bibendum. In pulvinar mauris non porttitor sagittis.</p>
  </div>
  <div class="col-lg-6 col-sm-12 parts-center">
    <img style="width: 15px; margin-bottom: 4px;" src="/resources/images/copyleft.png" alt="copyleft"> <?= SITE_NAME; ?> 2017
    <br/>
    <br/>
    <a href="<?= getUrl('contact'); ?>" class="btn btn-primary" title="Page de contact">
      <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
      Contact
    </a>
    <a href="<?= getUrl('mentions'); ?>" class="btn btn-primary" title="Mentions légales">
      <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
      Mentions légales
    </a>
    <br/>
    <br/>
    Developped and designed by Nicolas Buffart<br/>
    <a href="mailto:<?= WEBMASTER_MAIL; ?>" title="Contacter le webmaster par email">&lt;<?= WEBMASTER_MAIL; ?>&gt;</a>
  </div>
  <div class="col-lg-3 col-sm-12 visibilite">
    <h3>Visibilité</h3>
    <a href="" title="GitHub" target="_blank"><img class="image-pied" src="/resources/images/footer/github.png" alt="GitHub"/></a>
    <a href="" title="Twitter" target="_blank"><img class="image-pied" src="/resources/images/footer/twitter.png" alt="Twitter"/></a>
    <a href="" title="Facebook" target="_blank"><img class="image-pied" src="/resources/images/footer/fb.png" alt="Facebook"/></a>
    <a href="" title="LinkedIn" target="_blank"><img class="image-pied" src="/resources/images/footer/linkedin.png" alt="LinkedIn"/></a>
  </div>
</section>