<section class="row pied">
    <div class="col-md-3 parts-left">
        <h3>A propos</h3>
        <p>BlaBlaBla...</p>
    </div>
    <div class="col-md-6 parts-center">
        <img style="width: 15px; margin-bottom: 4px;" src="/resources/images/copyleft.png" alt="copyleft"> <?= SITE_NAME; ?> 2017 -
        <a href="<?= getUrl('contact'); ?>" class="btn btn-primary">
            <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
            Contact
        </a>
        <a href="<?= getUrl('mentions'); ?>" class="btn btn-primary">
            <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
            Mentions légales
        </a>
        <br/>
        <br/>
        Developped and designed by Nicolas Buffart<br/><a href="mailto:<?= WEBMASTER_MAIL; ?>">&lt;<?= WEBMASTER_MAIL; ?>&gt;</a>
    </div>
    <div class="col-md-3 visibilite">
        <h3>Visibilité</h3>
        <a href="" target="_blank"><img class="image-pied" src="/resources/images/footer/github.png"/></a>
        <a href="" target="_blank"><img class="image-pied" src="/resources/images/footer/twitter.png"/></a>
        <a href="" target="_blank"><img class="image-pied" src="/resources/images/footer/fb.png"/></a>
        <a href="" target="_blank"><img class="image-pied" src="/resources/images/footer/linkedin.png"/></a>
    </div>
</section>