<section class="row pied">
    <div class="col-md-3 parts-left">
        <h3>A propos</h3>
        <p>BlaBlaBla...</p>
    </div>
    <div class="col-md-6 parts-center">
        &copy; <?= SITE_NAME; ?> 2016 tous droits réservés -
        <a href="<?= getUrl('contact'); ?>" class="btn btn-success">
            <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
            Contact
        </a>
        <a href="<?= getUrl('mentions'); ?>" class="btn btn-success">
            <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
            Mentions légales
        </a>
    </div>
    <div class="col-md-3 visibilite">
        <h3>Visibilité</h3>
        <a href="" target="_blank"><img class="image-pied" src="<?= IMG; ?>/footer/github.png"/></a>
        <a href="" target="_blank"><img class="image-pied" src="<?= IMG; ?>/footer/twitter.png"/></a>
        <a href="" target="_blank"><img class="image-pied" src="<?= IMG; ?>/footer/fb.png"/></a>
        <a href="" target="_blank"><img class="image-pied" src="<?= IMG; ?>/footer/linkedin.png"/></a>
    </div>
</section>