<?php if (VERSION === 'dev') { ?>
    <link rel="stylesheet" href="/resources/css/bootstrap.min.css" type="text/css"/>
    <link rel="stylesheet" href="/resources/css/bootstrap-grid.css" type="text/css"/>
    <link rel="stylesheet" href="/resources/css/bootstrap-reboot.min.css" type="text/css"/>
<?php } else { ?>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<?php } ?>
<link rel="stylesheet" href="/resources/css/style.css" type="text/css"/>
<link rel="icon" href="/resources/images/icone.png">
<?=
printCssAssets($styles ?? '');
