<?php

use Itval\core\Classes\Asset;

if (VERSION === 'dev') {
    echo Asset::getAssetCss('bootstrap.min.css');
    echo Asset::getAssetCss('bootstrap-theme.min.css');
    echo Asset::getAssetCss('bootstrap-toggle.min.css');
} else {
    echo Asset::getAssetCss('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css',
        true,
        ['integrity' => 'sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u',
            'crossorigin' => 'anonymous']);
    echo Asset::getAssetCss('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css',
        true,
        ['integrity' => 'sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp',
            'crossorigin' => 'anonymous']);
    echo Asset::getAssetCss('https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css',
        true);
}

echo Asset::getAssetCss('style.css');
echo Asset::getAssetIcon('icone.png');
echo printCssAssets($styles ?? '');