<nav class="navbar navbar-expand-lg navbar-light fixed-top bg-light">
  <a class="navbar-brand" href="<?= BASE_URL; ?>">
    <img src="/resources/images/logo.png" width="30" height="30" class="d-inline-block align-top" alt="ITVAL"> <?= TITLE; ?>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link" href="#">Link</a>
      <a class="nav-item nav-link" href="#">Link</a>
      <a class="nav-item nav-link" href="#">Link</a>
      <a class="nav-item nav-link<?= isActiveLink(getUrl('contact')); ?>" href="<?= getUrl('contact'); ?>" title="Page de contact">
        Contact
      </a>
    </div>
  </div>
</nav>