<div class="row">
    <div class="col-md-12">
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
          <span class="navbar-brand">
            <img alt="Brand" src="<?= IMG . DS . 'icone.png'; ?>">
          </span>
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="navbar-brand"><?= TITLE; ?></div>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li<?= isActiveLink(); ?>><a href="<?= BASE_URL; ?>"><span
                                        class="glyphicon glyphicon-home" aria-hidden="true"></span> Accueil</a></li>
                        <li><a href="#">Lien</a></li>
                        <li><a href="#">Lien</a></li>
                        <li><a href="#">Lien</a></li>
                        <li<?= isActiveLink(getUrl('contact')); ?>><a href="<?= getUrl('contact'); ?>"><span
                                        class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Contact</a></li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    </div>
</div>