<?php

if (VERSION === 'dev') {
    echo '<script src="/resources/js/jquery.js"></script>';
    echo '<script src="/resources/js/bootstrap.min.js"></script>';
    echo '<script src="/resources/js/bootstrap-toggle.min.js"></script>';
} else {
    echo '<script
              src="https://code.jquery.com/jquery-3.2.1.min.js"
              integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
              crossorigin="anonymous">
          </script>';
    echo '<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>';
    echo '<script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>';
}
echo '<script src="/resources/js/ckeditor/ckeditor.js"></script>';
echo '<script src="/resources/js/functions.js"></script>';
echo printJsAssets($scripts ?? '');